name: Build and Release

on:
  workflow_dispatch:
    inputs:
      build-trigger:
        description: 'Trigger the build'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build Exe
        run: pyinstaller --onefile yt-dlpGUI.py

      - name: Create bin folder
        run: mkdir bin

      - name: Move exe and help.txt
        run: |
          mv dist/yt-dlpGUI bin/

      - name: Zip files
        run: zip -r yt-dlpGUI.zip bin/

      - name: Upload to release
        uses: actions/upload-artifact@v2
        with:
          name: yt-dlpGUI
          path: yt-dlpGUI.zip