name: Build and Release

on:
  workflow_dispatch:
    inputs:
      build-trigger:
        description: 'Build'

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5

      - name: Install dependencies
        run: |
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile yt-dlpGUI.py

      - name: Create Release
        id: create_release
        run: |
          mkdir bin
          mv dist/yt-dlpGUI bin/
          cp help.txt bin/
          zip -r release.zip bin/

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: yt-dlpGUI_release.zip
          asset_content_type: application/zip

  create_release:
    needs: build_and_release
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ needs.build_and_release.outputs.version }}
          release_name: Release v${{ needs.build_and_release.outputs.version }}
          draft: false
          prerelease: false